import 'package:flutter/material.dart';

/// Represents a predefined application theme palette.
class AppThemePreset {
  final String id;
  final String name;
  final String description;
  final ColorScheme lightScheme;
  final ColorScheme darkScheme;
  final Color previewLightBackground;
  final Color previewDarkBackground;
  final Color previewAccent;

  const AppThemePreset({
    required this.id,
    required this.name,
    required this.description,
    required this.lightScheme,
    required this.darkScheme,
    required this.previewLightBackground,
    required this.previewDarkBackground,
    required this.previewAccent,
  });

  /// Preset identifier for the default theme.
  static const String defaultPresetId = 'sepia';

  /// Preset identifier for the custom user-defined theme.
  static const String customPresetId = 'custom';

  /// Collection of curated reading themes.
  static final List<AppThemePreset> all = [
    _sepia,
    _paper,
    _stone,
    _purple,
    _charcoal,
    _oled,
    _ocean,
  ];

  /// Look up a preset by its ID. Falls back to default Sepia Parchment theme.
  static AppThemePreset findById(String id) {
    return all.firstWhere(
      (preset) => preset.id == id,
      orElse: () => _sepia,
    );
  }

  // 2. Clean Paper
  static final _paper = AppThemePreset(
    id: 'paper',
    name: 'Clean Paper',
    description: 'Crisp white and dark slate with biblical navy accents.',
    lightScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF1A5A96),
      surfaceTint: Color(0xFF1A5A96),
      onPrimary: Colors.white,
      primaryContainer: Color(0xFFD6E4FF),
      onPrimaryContainer: Color(0xFF001B3E),
      secondary: Color(0xFF526070),
      onSecondary: Colors.white,
      secondaryContainer: Color(0xFFD5E4F7),
      onSecondaryContainer: Color(0xFF0F1D2A),
      tertiary: Color(0xFF6B5778),
      onTertiary: Colors.white,
      tertiaryContainer: Color(0xFFF3DAFF),
      onTertiaryContainer: Color(0xFF251432),
      error: Color(0xFFBA1A1A),
      onError: Colors.white,
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF191C1E),
      onSurfaceVariant: Color(0xFF41474D),
      outline: Color(0xFF72787E),
      outlineVariant: Color(0xFFC1C7CE),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFF2E3133),
      inversePrimary: Color(0xFFA6C8FF),
      surfaceDim: Color(0xFFD8DADD),
      surfaceBright: Color(0xFFFFFFFF),
      surfaceContainerLowest: Colors.white,
      surfaceContainerLow: Color(0xFFF7F9FB),
      surfaceContainer: Color(0xFFF1F4F7),
      surfaceContainerHigh: Color(0xFFEBEFF2),
      surfaceContainerHighest: Color(0xFFE2E6EA),
    ),
    darkScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFA6C8FF),
      surfaceTint: Color(0xFFA6C8FF),
      onPrimary: Color(0xFF003060),
      primaryContainer: Color(0xFF004786),
      onPrimaryContainer: Color(0xFFD6E4FF),
      secondary: Color(0xFFBAC8DB),
      onSecondary: Color(0xFF243140),
      secondaryContainer: Color(0xFF3B4858),
      onSecondaryContainer: Color(0xFFD5E4F7),
      tertiary: Color(0xFFD6BEE4),
      onTertiary: Color(0xFF3B2948),
      tertiaryContainer: Color(0xFF52405F),
      onTertiaryContainer: Color(0xFFF3DAFF),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF131517),
      onSurface: Color(0xFFE2E2E6),
      onSurfaceVariant: Color(0xFFC1C7CE),
      outline: Color(0xFF8B9198),
      outlineVariant: Color(0xFF41474D),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFFE2E2E6),
      inversePrimary: Color(0xFF1A5A96),
      surfaceDim: Color(0xFF101214),
      surfaceBright: Color(0xFF35383C),
      surfaceContainerLowest: Color(0xFF0E1012),
      surfaceContainerLow: Color(0xFF1B1D20),
      surfaceContainer: Color(0xFF1F2225),
      surfaceContainerHigh: Color(0xFF2A2D30),
      surfaceContainerHighest: Color(0xFF35383C),
    ),
    previewLightBackground: const Color(0xFFFFFFFF),
    previewDarkBackground: const Color(0xFF131517),
    previewAccent: const Color(0xFF1A5A96),
  );

  // 3. Sepia Parchment
  static final _sepia = AppThemePreset(
    id: 'sepia',
    name: 'Sepia Parchment',
    description: 'Warm, restful paper tones that minimize eye fatigue.',
    lightScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF865328),
      surfaceTint: Color(0xFF865328),
      onPrimary: Colors.white,
      primaryContainer: Color(0xFFFFDCC5),
      onPrimaryContainer: Color(0xFF301400),
      secondary: Color(0xFF6F5B40),
      onSecondary: Colors.white,
      secondaryContainer: Color(0xFFFBE0BE),
      onSecondaryContainer: Color(0xFF271904),
      tertiary: Color(0xFF55624C),
      onTertiary: Colors.white,
      tertiaryContainer: Color(0xFFD8E7CC),
      onTertiaryContainer: Color(0xFF131F0E),
      error: Color(0xFFBA1A1A),
      onError: Colors.white,
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFF7F1E5),
      onSurface: Color(0xFF2D2319),
      onSurfaceVariant: Color(0xFF534538),
      outline: Color(0xFF857466),
      outlineVariant: Color(0xFFD7C3B3),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFF393026),
      inversePrimary: Color(0xFFFFB68C),
      surfaceDim: Color(0xFFDFD9CD),
      surfaceBright: Color(0xFFFFFBF5),
      surfaceContainerLowest: Color(0xFFFFFBF5),
      surfaceContainerLow: Color(0xFFF2ECE0),
      surfaceContainer: Color(0xFFECE6DA),
      surfaceContainerHigh: Color(0xFFE6E0D4),
      surfaceContainerHighest: Color(0xFFE0DACF),
    ),
    darkScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB68C),
      surfaceTint: Color(0xFFFFB68C),
      onPrimary: Color(0xFF4D2600),
      primaryContainer: Color(0xFF6C3C12),
      onPrimaryContainer: Color(0xFFFFDCC5),
      secondary: Color(0xFFDEC2A0),
      onSecondary: Color(0xFF3E2D16),
      secondaryContainer: Color(0xFF56432A),
      onSecondaryContainer: Color(0xFFFBE0BE),
      tertiary: Color(0xFFBDCBB1),
      onTertiary: Color(0xFF273421),
      tertiaryContainer: Color(0xFF3D4A36),
      onTertiaryContainer: Color(0xFFD8E7CC),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF1E1813),
      onSurface: Color(0xFFECE0D5),
      onSurfaceVariant: Color(0xFFD7C3B3),
      outline: Color(0xFFA08E7F),
      outlineVariant: Color(0xFF534538),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFFECE0D5),
      inversePrimary: Color(0xFF865328),
      surfaceDim: Color(0xFF1A1410),
      surfaceBright: Color(0xFF403933),
      surfaceContainerLowest: Color(0xFF17120E),
      surfaceContainerLow: Color(0xFF251F19),
      surfaceContainer: Color(0xFF2A241E),
      surfaceContainerHigh: Color(0xFF352E28),
      surfaceContainerHighest: Color(0xFF403933),
    ),
    previewLightBackground: const Color(0xFFF7F1E5),
    previewDarkBackground: const Color(0xFF1E1813),
    previewAccent: const Color(0xFF865328),
  );

  // 4. Quiet Sage
  static final _stone = AppThemePreset(
    id: 'stone',
    name: 'Quiet Sage',
    description: 'Soothing natural green and slate tones for extended study.',
    lightScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF386646),
      surfaceTint: Color(0xFF386646),
      onPrimary: Colors.white,
      primaryContainer: Color(0xFFBAECC5),
      onPrimaryContainer: Color(0xFF00210E),
      secondary: Color(0xFF4F6352),
      onSecondary: Colors.white,
      secondaryContainer: Color(0xFFD2E8D3),
      onSecondaryContainer: Color(0xFF0D1F12),
      tertiary: Color(0xFF3A646F),
      onTertiary: Colors.white,
      tertiaryContainer: Color(0xFFBEEAF7),
      onTertiaryContainer: Color(0xFF001F26),
      error: Color(0xFFBA1A1A),
      onError: Colors.white,
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFEBF0E9),
      onSurface: Color(0xFF19201A),
      onSurfaceVariant: Color(0xFF424941),
      outline: Color(0xFF727970),
      outlineVariant: Color(0xFFC2C9BE),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFF2E342E),
      inversePrimary: Color(0xFF9FD0AA),
      surfaceDim: Color(0xFFD6DCD4),
      surfaceBright: Color(0xFFF4F9F2),
      surfaceContainerLowest: Color(0xFFF4F9F2),
      surfaceContainerLow: Color(0xFFE5EAE3),
      surfaceContainer: Color(0xFFDFE4DD),
      surfaceContainerHigh: Color(0xFFD9DFD7),
      surfaceContainerHighest: Color(0xFFD3D9D1),
    ),
    darkScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF9FD0AA),
      surfaceTint: Color(0xFF9FD0AA),
      onPrimary: Color(0xFF03381B),
      primaryContainer: Color(0xFF204E30),
      onPrimaryContainer: Color(0xFFBAECC5),
      secondary: Color(0xFFB6CCB8),
      onSecondary: Color(0xFF223526),
      secondaryContainer: Color(0xFF384B3C),
      onSecondaryContainer: Color(0xFFD2E8D3),
      tertiary: Color(0xFFA2CEDB),
      onTertiary: Color(0xFF01363F),
      tertiaryContainer: Color(0xFF204D56),
      onTertiaryContainer: Color(0xFFBEEAF7),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF131A15),
      onSurface: Color(0xFFDFE6DE),
      onSurfaceVariant: Color(0xFFC2C9BE),
      outline: Color(0xFF8C9389),
      outlineVariant: Color(0xFF424941),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFFDFE6DE),
      inversePrimary: Color(0xFF386646),
      surfaceDim: Color(0xFF101611),
      surfaceBright: Color(0xFF353E37),
      surfaceContainerLowest: Color(0xFF0E1410),
      surfaceContainerLow: Color(0xFF1A221C),
      surfaceContainer: Color(0xFF202822),
      surfaceContainerHigh: Color(0xFF2A332C),
      surfaceContainerHighest: Color(0xFF353E37),
    ),
    previewLightBackground: const Color(0xFFEBF0E9),
    previewDarkBackground: const Color(0xFF131A15),
    previewAccent: const Color(0xFF386646),
  );

  // 5. Royal Purple
  static final _purple = AppThemePreset(
    id: 'purple',
    name: 'Royal Purple',
    description: 'Gentle lavender paper and deep velvet plum with royal amethyst accents.',
    lightScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF6E3A8C),
      surfaceTint: Color(0xFF6E3A8C),
      onPrimary: Colors.white,
      primaryContainer: Color(0xFFF0DCFD),
      onPrimaryContainer: Color(0xFF290043),
      secondary: Color(0xFF65576E),
      onSecondary: Colors.white,
      secondaryContainer: Color(0xFFEDDEF5),
      onSecondaryContainer: Color(0xFF211529),
      tertiary: Color(0xFF7C5264),
      onTertiary: Colors.white,
      tertiaryContainer: Color(0xFFFFD8E7),
      onTertiaryContainer: Color(0xFF311020),
      error: Color(0xFFBA1A1A),
      onError: Colors.white,
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFF6F2F8),
      onSurface: Color(0xFF25182E),
      onSurfaceVariant: Color(0xFF5E4F68),
      outline: Color(0xFF7C7284),
      outlineVariant: Color(0xFFCDC2D5),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFF332A39),
      inversePrimary: Color(0xFFD8B2FF),
      surfaceDim: Color(0xFFDFD8E2),
      surfaceBright: Color(0xFFFCF8FD),
      surfaceContainerLowest: Colors.white,
      surfaceContainerLow: Color(0xFFF1ECF4),
      surfaceContainer: Color(0xFFEBE5EE),
      surfaceContainerHigh: Color(0xFFE5DFE8),
      surfaceContainerHighest: Color(0xFFDFD9E3),
    ),
    darkScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFD8B2FF),
      surfaceTint: Color(0xFFD8B2FF),
      onPrimary: Color(0xFF3E0067),
      primaryContainer: Color(0xFF562373),
      onPrimaryContainer: Color(0xFFF0DCFD),
      secondary: Color(0xFFCEBFD8),
      onSecondary: Color(0xFF352B3E),
      secondaryContainer: Color(0xFF4C4155),
      onSecondaryContainer: Color(0xFFEDDEF5),
      tertiary: Color(0xFFEDB8CE),
      onTertiary: Color(0xFF482535),
      tertiaryContainer: Color(0xFF623B4C),
      onTertiaryContainer: Color(0xFFFFD8E7),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF17121C),
      onSurface: Color(0xFFEDE3F2),
      onSurfaceVariant: Color(0xFFC9BDD2),
      outline: Color(0xFF968B9E),
      outlineVariant: Color(0xFF4B4252),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFFEDE3F2),
      inversePrimary: Color(0xFF6E3A8C),
      surfaceDim: Color(0xFF140F18),
      surfaceBright: Color(0xFF38313D),
      surfaceContainerLowest: Color(0xFF110C15),
      surfaceContainerLow: Color(0xFF1D1722),
      surfaceContainer: Color(0xFF221C27),
      surfaceContainerHigh: Color(0xFF2C2632),
      surfaceContainerHighest: Color(0xFF38313D),
    ),
    previewLightBackground: const Color(0xFFF6F2F8),
    previewDarkBackground: const Color(0xFF17121C),
    previewAccent: const Color(0xFF6E3A8C),
  );

  // 6. Night Charcoal
  static final _charcoal = AppThemePreset(
    id: 'charcoal',
    name: 'Night Charcoal',
    description: 'Comfortable charcoal dark palette with warm candlelight accents.',
    lightScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF3B607D),
      surfaceTint: Color(0xFF3B607D),
      onPrimary: Colors.white,
      primaryContainer: Color(0xFFD3E4FF),
      onPrimaryContainer: Color(0xFF001C38),
      secondary: Color(0xFF545F6E),
      onSecondary: Colors.white,
      secondaryContainer: Color(0xFFD8E3F5),
      onSecondaryContainer: Color(0xFF111C29),
      tertiary: Color(0xFF6C5778),
      onTertiary: Colors.white,
      tertiaryContainer: Color(0xFFF4DAFF),
      onTertiaryContainer: Color(0xFF261432),
      error: Color(0xFFBA1A1A),
      onError: Colors.white,
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFF3F5F7),
      onSurface: Color(0xFF1A1C1E),
      onSurfaceVariant: Color(0xFF43474E),
      outline: Color(0xFF74777F),
      outlineVariant: Color(0xFFC4C7D0),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFF2F3133),
      inversePrimary: Color(0xFFA2C9EE),
      surfaceDim: Color(0xFFD8DADD),
      surfaceBright: Color(0xFFFBFDFF),
      surfaceContainerLowest: Colors.white,
      surfaceContainerLow: Color(0xFFECEEF1),
      surfaceContainer: Color(0xFFE6E8EB),
      surfaceContainerHigh: Color(0xFFE0E3E6),
      surfaceContainerHighest: Color(0xFFDBDEE1),
    ),
    darkScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFE5B869),
      surfaceTint: Color(0xFFE5B869),
      onPrimary: Color(0xFF3F2E00),
      primaryContainer: Color(0xFF5B4300),
      onPrimaryContainer: Color(0xFFFFDF9E),
      secondary: Color(0xFFD1C5B4),
      onSecondary: Color(0xFF372F23),
      secondaryContainer: Color(0xFF4E4539),
      onSecondaryContainer: Color(0xFFEEE1D0),
      tertiary: Color(0xFFB5CEA9),
      onTertiary: Color(0xFF22351C),
      tertiaryContainer: Color(0xFF384C31),
      onTertiaryContainer: Color(0xFFD1EAB4),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF1A1C1E),
      onSurface: Color(0xFFE2E2E6),
      onSurfaceVariant: Color(0xFFC4C7D0),
      outline: Color(0xFF8E9099),
      outlineVariant: Color(0xFF43474E),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFFE2E2E6),
      inversePrimary: Color(0xFF755B00),
      surfaceDim: Color(0xFF151719),
      surfaceBright: Color(0xFF3D3F43),
      surfaceContainerLowest: Color(0xFF141618),
      surfaceContainerLow: Color(0xFF222427),
      surfaceContainer: Color(0xFF27292C),
      surfaceContainerHigh: Color(0xFF323438),
      surfaceContainerHighest: Color(0xFF3D3F43),
    ),
    previewLightBackground: const Color(0xFFF3F5F7),
    previewDarkBackground: const Color(0xFF1A1C1E),
    previewAccent: const Color(0xFFE5B869),
  );

  // 6. OLED Pure Black
  static final _oled = AppThemePreset(
    id: 'oled',
    name: 'OLED Pure Black',
    description: 'True pitch-black background optimized for OLED screens.',
    lightScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF202020),
      surfaceTint: Color(0xFF202020),
      onPrimary: Colors.white,
      primaryContainer: Color(0xFFE0E0E0),
      onPrimaryContainer: Colors.black,
      secondary: Color(0xFF4A4A4A),
      onSecondary: Colors.white,
      secondaryContainer: Color(0xFFEBEBEB),
      onSecondaryContainer: Color(0xFF101010),
      tertiary: Color(0xFF555555),
      onTertiary: Colors.white,
      tertiaryContainer: Color(0xFFECECEC),
      onTertiaryContainer: Color(0xFF121212),
      error: Color(0xFFBA1A1A),
      onError: Colors.white,
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Colors.white,
      onSurface: Colors.black,
      onSurfaceVariant: Color(0xFF3C3C3C),
      outline: Color(0xFF707070),
      outlineVariant: Color(0xFFC6C6C6),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFF222222),
      inversePrimary: Color(0xFFE0E0E0),
      surfaceDim: Color(0xFFD6D6D6),
      surfaceBright: Colors.white,
      surfaceContainerLowest: Colors.white,
      surfaceContainerLow: Color(0xFFF7F7F7),
      surfaceContainer: Color(0xFFF0F0F0),
      surfaceContainerHigh: Color(0xFFE8E8E8),
      surfaceContainerHighest: Color(0xFFDFDFDF),
    ),
    darkScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFD4AF37),
      surfaceTint: Color(0xFFD4AF37),
      onPrimary: Color(0xFF352A00),
      primaryContainer: Color(0xFF4E3E00),
      onPrimaryContainer: Color(0xFFFFDF7A),
      secondary: Color(0xFFC8C8C8),
      onSecondary: Color(0xFF202020),
      secondaryContainer: Color(0xFF323232),
      onSecondaryContainer: Color(0xFFE0E0E0),
      tertiary: Color(0xFFB0B0B0),
      onTertiary: Color(0xFF1A1A1A),
      tertiaryContainer: Color(0xFF2E2E2E),
      onTertiaryContainer: Color(0xFFCCCCCC),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Colors.black,
      onSurface: Color(0xFFE0E0E0),
      onSurfaceVariant: Color(0xFFA0A0A0),
      outline: Color(0xFF606060),
      outlineVariant: Color(0xFF2E2E2E),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFFE0E0E0),
      inversePrimary: Color(0xFF695400),
      surfaceDim: Colors.black,
      surfaceBright: Color(0xFF242424),
      surfaceContainerLowest: Colors.black,
      surfaceContainerLow: Color(0xFF0B0B0B),
      surfaceContainer: Color(0xFF121212),
      surfaceContainerHigh: Color(0xFF1A1A1A),
      surfaceContainerHighest: Color(0xFF242424),
    ),
    previewLightBackground: const Color(0xFFFFFFFF),
    previewDarkBackground: const Color(0xFF000000),
    previewAccent: const Color(0xFFD4AF37),
  );

  // 7. Midnight Ocean
  static final _ocean = AppThemePreset(
    id: 'ocean',
    name: 'Midnight Ocean',
    description: 'Deep maritime navy with luminous sky blue accents.',
    lightScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF0B588C),
      surfaceTint: Color(0xFF0B588C),
      onPrimary: Colors.white,
      primaryContainer: Color(0xFFCBE6FF),
      onPrimaryContainer: Color(0xFF001E35),
      secondary: Color(0xFF4C6173),
      onSecondary: Colors.white,
      secondaryContainer: Color(0xFFCFE5FB),
      onSecondaryContainer: Color(0xFF071E2D),
      tertiary: Color(0xFF65587B),
      onTertiary: Colors.white,
      tertiaryContainer: Color(0xFFECDCFF),
      onTertiaryContainer: Color(0xFF211634),
      error: Color(0xFFBA1A1A),
      onError: Colors.white,
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFF1F5F9),
      onSurface: Color(0xFF0F1B26),
      onSurfaceVariant: Color(0xFF404850),
      outline: Color(0xFF717981),
      outlineVariant: Color(0xFFC0C7CF),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFF2A3138),
      inversePrimary: Color(0xFF88C9FA),
      surfaceDim: Color(0xFFD5DBE1),
      surfaceBright: Color(0xFFF9FBFF),
      surfaceContainerLowest: Colors.white,
      surfaceContainerLow: Color(0xFFEAEFF5),
      surfaceContainer: Color(0xFFE4EBF2),
      surfaceContainerHigh: Color(0xFFDEE5EC),
      surfaceContainerHighest: Color(0xFFD8DFE6),
    ),
    darkScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF88C9FA),
      surfaceTint: Color(0xFF88C9FA),
      onPrimary: Color(0xFF00344F),
      primaryContainer: Color(0xFF004B70),
      onPrimaryContainer: Color(0xFFCBE6FF),
      secondary: Color(0xFFB4C8DE),
      onSecondary: Color(0xFF1E3243),
      secondaryContainer: Color(0xFF35485B),
      onSecondaryContainer: Color(0xFFCFE5FB),
      tertiary: Color(0xFFD0C0E8),
      onTertiary: Color(0xFF362B4A),
      tertiaryContainer: Color(0xFF4D4162),
      onTertiaryContainer: Color(0xFFECDCFF),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      surface: Color(0xFF0B131E),
      onSurface: Color(0xFFDAE3EE),
      onSurfaceVariant: Color(0xFFC0C7CF),
      outline: Color(0xFF8A929A),
      outlineVariant: Color(0xFF404850),
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFFDAE3EE),
      inversePrimary: Color(0xFF0B588C),
      surfaceDim: Color(0xFF080F18),
      surfaceBright: Color(0xFF253750),
      surfaceContainerLowest: Color(0xFF060B12),
      surfaceContainerLow: Color(0xFF101C2B),
      surfaceContainer: Color(0xFF142234),
      surfaceContainerHigh: Color(0xFF1C2C42),
      surfaceContainerHighest: Color(0xFF253750),
    ),
    previewLightBackground: const Color(0xFFF1F5F9),
    previewDarkBackground: const Color(0xFF0B131E),
    previewAccent: const Color(0xFF88C9FA),
  );
}
