name: bsb
description: "Berean Standard Bible"
publish_to: 'none' 
version: 0.7.0+8

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  get_it: ^8.0.3
  path: ^1.9.0
  database_builder: 
    path: ../database_builder
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/database/database.db

  # The printed version uses Cambria, but this apparently isn't free to use in an app.
  fonts:
    - family: Charis
      fonts:
        - asset: assets/fonts/CharisSIL-Regular.ttf
        - asset: assets/fonts/CharisSIL-Italic.ttf
          style: italic
        - asset: assets/fonts/CharisSIL-Bold.ttf
          weight: 700 # bold
