name: database_builder
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  sqflite: ^2.4.1
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
